version: "3"
services:
  pmweb-hotel:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_USER=testepmweb
      - MONGO_PASSWORD=teste123
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
    command: npm run prod

  pmweb-hotel-test:
    build: .
    environment:
      - MONGO_USER=testepmweb
      - MONGO_PASSWORD=teste123
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
    command: npm test
    # Evita que o serviço fique executando continuamente no modo watch
    restart: "no"

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testepmweb
      - MONGO_INITDB_ROOT_PASSWORD=teste123

volumes:
  mongo-db:
