name: Teste de Integração com Jest

on:
  push:
    branches:
      - main  # Ou a branch que você preferir
  pull_request:
    branches:
      - main  # Ou a branch que você preferir

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar repositório
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ou qualquer outra versão do Node.js que você preferir

    - name: Instalar dependências
      run: npm install

    - name: Executar testes com Jest
      run: npm test
